version: '3.8'

services:
  chatbot-ui:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    restart: unless-stopped
    depends_on:
      - mcp-server
    networks:
      - app-network

  mcp-server:
    build:
      context: ./chatbot-integrations/unified-mcp
      dockerfile: Dockerfile
    ports:
      - "3009:3009"
    environment:
      - PORT=3009
      # Jenkins Config
      - JENKINS_URL=http://jenkins:8080
      - JENKINS_USER=admin
      - JENKINS_TOKEN=admin
      # MCP Config Paths
      - JIRA_CONFIG_PATH=/app/config/jira.config.json
      - SONAR_CONFIG_PATH=/app/config/sonarqube.config.json
      - NEXUS_CONFIG_PATH=/app/config/nexus.config.json
      - BITBUCKET_CONFIG_PATH=/app/config/bitbucket.config.json
      - ELASTIC_CONFIG_PATH=/app/config/elasticsearch.config.json
      - GRAFANA_CONFIG_PATH=/app/config/grafana.config.json
    volumes:
      - ./chatbot-integrations/jira/sourcecode/jira.config.json:/app/config/jira.config.json:ro
      - ./chatbot-integrations/sonarqube/sourcecode/sonarqube.config.json:/app/config/sonarqube.config.json:ro
      - ./chatbot-integrations/nexus/sourcecode/nexus.config.json:/app/config/nexus.config.json:ro
      - ./chatbot-integrations/bitbucket/sourcecode/bitbucket.config.json:/app/config/bitbucket.config.json:ro
      - ./chatbot-integrations/elasticsearch/sourcecode/elasticsearch.config.json:/app/config/elasticsearch.config.json:ro
      - ./chatbot-integrations/grafana/sourcecode/grafana.config.json:/app/config/grafana.config.json:ro
    restart: always
    networks:
      - app-network
    depends_on:
      - jenkins
    healthcheck:
      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3009/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3

  jenkins:
    image: jenkins/jenkins:jdk21
    ports:
      - "7080:8080"
      - "60000:50000"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - jenkins_home:/var/jenkins_home

networks:
  app-network:
    driver: bridge

volumes:
  jenkins_home:
